<a href="https://colab.research.google.com/github/mylhb9/Homework/blob/master/%EC%97%B4%EC%9C%A0%EC%B2%B4%EA%B3%B5%ED%95%99%EC%8B%A4%ED%97%98-2017026508-HW04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#기본 문법을 사용한 방법
def multiplication():
  a=int(input())
  for i in range (1,10):
    b=a*i
    print(b)
z=multiplication()
%timeit z

5
5
10
15
20
25
30
35
40
45
100000000 loops, best of 3: 16.6 ns per loop


In [31]:
#numpy를 사용한 방법
import numpy as np
print("구구단을 알고 싶은 숫자를 입력하시오.")
a= int(input())
x=np.arange(1,10)*a
print(x)
%timeit x

구구단을 알고 싶은 숫자를 입력하시오.
5
[ 5 10 15 20 25 30 35 40 45]
100000000 loops, best of 3: 19.6 ns per loop


In [32]:
#numba.jit를 사용한 방법
import numba
@numba.jit("void(f4[:])")
def mult(x):
  return np.arange(1,10)*x
a=int(input())
k=mult(a)
print(k)
%timeit k

5
[ 5 10 15 20 25 30 35 40 45]
100000000 loops, best of 3: 15.4 ns per loop


In [33]:
#cuda를 사용한 방법
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.1/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so"

import numpy as np
from numba import vectorize

a= int(input())
b= np.arange(1,10)

@vectorize(['int64(int64, int64)'], target='cuda')
def mul_ufunc(x, y):
    return x * y

print(mul_ufunc(a, b))
%timeit mul_ufunc(a,b)

5
[ 5 10 15 20 25 30 35 40 45]
1000 loops, best of 3: 814 µs per loop
